version: '3.7'
services:
  db:
    image: postgres:latest
    volumes:
      - "data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    restart: always
  adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080
  svelte:
      build: svelte/
      container_name: svelte
      ports:
        - 8181:8181
      volumes:
        - "svelteDir:/home/svelte"
      networks:
        - trans
  nest:
      build: nest/
      container_name: nest
      ports:
        - 3434:3434
      volumes:
        - "nest:/home/nest"
      networks:
        - trans
  prisma:
      build: prisma/
      container_name: prisma
      ports:
        - 4466:4466
      volumes:
        - "prisma:/home/prisma"
      networks:
        - trans
      depends_on:
        - "db"
      restart: always

networks:
  trans:

volumes:
  data:
  svelteDir:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: "${PWD}/svelte/srcs"
  nest:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: "${PWD}/nest/srcs"
  prisma:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: "${PWD}/prisma/srcs"
